const PDFDocument = require('pdfkit')
const { PassThrough } = require('stream')
const { uploadToR2 } = require('./r2')

function camelToLabel(key) {
  return key.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()).trim()
}

function formatValue(v) {
  if (v === null || v === undefined || v === '') return '—'
  if (typeof v === 'boolean') return v ? 'Yes' : 'No'
  if (Array.isArray(v)) {
    if (v.length === 0) return '—'
    if (typeof v[0] === 'object') return v.map(r => Object.entries(r).map(([k, val]) => `${k}: ${val}`).join(', ')).join('\n')
    return v.join(', ')
  }
  if (typeof v === 'object') return Object.entries(v).map(([k, val]) => `${camelToLabel(k)}: ${formatValue(val)}`).join('\n')
  const s = String(v)
  if (s.startsWith('data:image')) return '[Signature Image]'
  return s
}

async function generateSubmissionPDF(formName, submission, data) {
  const filename = `pdfs/submission-${submission.id}-${Date.now()}.pdf`

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' })
    const pass = new PassThrough()
    const chunks = []

    pass.on('data', chunk => chunks.push(chunk))
    pass.on('end', async () => {
      try {
        const buffer = Buffer.concat(chunks)
        const url = await uploadToR2(buffer, filename, 'application/pdf')
        resolve(url)
      } catch (err) {
        reject(err)
      }
    })
    pass.on('error', reject)
    doc.pipe(pass)

    // Header band
    doc.rect(0, 0, doc.page.width, 80).fill('#1e40af')
    doc.fillColor('white').fontSize(18).font('Helvetica-Bold')
      .text(formName, 50, 22, { align: 'center', width: doc.page.width - 100 })
    doc.fontSize(10).font('Helvetica')
      .text('Form Submission Report', 50, 46, { align: 'center', width: doc.page.width - 100 })

    doc.fillColor('#1f2937')
    let y = 100

    doc.fontSize(9).font('Helvetica')
    doc.text(`Submission ID: #${submission.id}`, 50, y)
    doc.text(`Submitted By: ${submission.submitted_by}`, 200, y)
    doc.text(`Date: ${new Date(submission.submitted_at).toLocaleString('en-MY')}`, 370, y)
    y += 16
    doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor('#e5e7eb').lineWidth(1).stroke()
    y += 12

    const fields = Object.entries(data).filter(([k]) => !k.startsWith('_'))
    fields.forEach(([key, value]) => {
      const label = camelToLabel(key)
      const valStr = formatValue(value)
      const valLines = valStr.split('\n')
      const neededHeight = 14 + valLines.length * 11
      if (y + neededHeight > doc.page.height - 70) { doc.addPage(); y = 50 }
      doc.font('Helvetica-Bold').fillColor('#374151').text(label + ':', 50, y, { width: 140, lineBreak: false })
      doc.font('Helvetica').fillColor('#1f2937')
      valLines.forEach((line, i) => {
        doc.text(line.length > 90 ? line.slice(0, 90) + '…' : line, 200, y + i * 11, { width: 350 })
      })
      y += neededHeight
      doc.moveTo(50, y - 2).lineTo(doc.page.width - 50, y - 2).strokeColor('#f3f4f6').lineWidth(0.5).stroke()
    })

    const files = data._files || {}
    if (Object.keys(files).length > 0) {
      if (y + 50 > doc.page.height - 70) { doc.addPage(); y = 50 }
      y += 6
      doc.moveTo(50, y).lineTo(doc.page.width - 50, y).strokeColor('#e5e7eb').lineWidth(1).stroke()
      y += 10
      doc.font('Helvetica-Bold').fontSize(10).fillColor('#374151').text('Attachments', 50, y)
      y += 14
      Object.entries(files).forEach(([field, fileList]) => {
        fileList.forEach(f => {
          if (y + 12 > doc.page.height - 70) { doc.addPage(); y = 50 }
          doc.font('Helvetica').fontSize(9).fillColor('#6b7280')
            .text(`• ${camelToLabel(field)}: ${f.originalname || f.url} (${Math.round((f.size || 0) / 1024)} KB)`, 60, y)
          y += 12
        })
      })
    }

    const footerY = doc.page.height - 40
    doc.moveTo(50, footerY - 8).lineTo(doc.page.width - 50, footerY - 8).strokeColor('#e5e7eb').lineWidth(0.5).stroke()
    doc.font('Helvetica').fontSize(8).fillColor('#9ca3af')
      .text(`Generated by Wanconnect Operations Portal · ${new Date().toLocaleString('en-MY')}`, 50, footerY, { align: 'center', width: doc.page.width - 100 })

    doc.end()
  })
}

module.exports = { generateSubmissionPDF }
